export default {"tracks": {
    "href": "https://api.spotify.com/v1/search?query=russ&type=track&market=US&offset=0&limit=10",
    "items": [
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/48Kac3ieDtt9OSp9Fm4g9e"
          },
          "href": "https://api.spotify.com/v1/albums/48Kac3ieDtt9OSp9Fm4g9e",
          "id": "48Kac3ieDtt9OSp9Fm4g9e",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/8edcbefd8cccc4a48d0579dcc74fe99f74f94b65",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/44eca21c38e12e205ac09b064595a4002b286112",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/a02b9f3a28c203353cc82fb5d853ad4421847750",
              "width": 64
            }
          ],
          "name": "ZOO",
          "release_date": "2018-09-07",
          "release_date_precision": "day",
          "total_tracks": 14,
          "type": "album",
          "uri": "spotify:album:48Kac3ieDtt9OSp9Fm4g9e"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 226693,
        "explicit": true,
        "external_ids": {
          "isrc": "USSM11806564"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4ve2uzqdwnHr20G5YgMMqr"
        },
        "href": "https://api.spotify.com/v1/tracks/4ve2uzqdwnHr20G5YgMMqr",
        "id": "4ve2uzqdwnHr20G5YgMMqr",
        "is_local": false,
        "name": "Missin You Crazy",
        "popularity": 82,
        "preview_url": "https://p.scdn.co/mp3-preview/243d04c0fe973b08258cd959625ac4a87371e0ea?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:4ve2uzqdwnHr20G5YgMMqr"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0lUL92det7mZ4DaHYmiUEC"
          },
          "href": "https://api.spotify.com/v1/albums/0lUL92det7mZ4DaHYmiUEC",
          "id": "0lUL92det7mZ4DaHYmiUEC",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/896e3f06b79792b93bb96ee3f3444a5a87ce845f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/7f5511ed5fd0c3d02ae19655a26a9b3ee6937f5b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/c09b87a7035848b413b642e6f3fa16a5992f4354",
              "width": 64
            }
          ],
          "name": "There's Really A Wolf",
          "release_date": "2017-05-05",
          "release_date_precision": "day",
          "total_tracks": 20,
          "type": "album",
          "uri": "spotify:album:0lUL92det7mZ4DaHYmiUEC"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 237506,
        "explicit": true,
        "external_ids": {
          "isrc": "USSM11606199"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4cxMGhkinTocPSVVKWIw0d"
        },
        "href": "https://api.spotify.com/v1/tracks/4cxMGhkinTocPSVVKWIw0d",
        "id": "4cxMGhkinTocPSVVKWIw0d",
        "is_local": false,
        "name": "Losin Control",
        "popularity": 79,
        "preview_url": "https://p.scdn.co/mp3-preview/b6912a2077507660710d39ae6ba5c085891dc226?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 14,
        "type": "track",
        "uri": "spotify:track:4cxMGhkinTocPSVVKWIw0d"
      },
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/21UO4eAaNZ5kultgMBNEHD"
          },
          "href": "https://api.spotify.com/v1/albums/21UO4eAaNZ5kultgMBNEHD",
          "id": "21UO4eAaNZ5kultgMBNEHD",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/710f84e2228cba2e6d86a4ad86e6b80449a72d34",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/1131f6479ae732a76735cb365051dc4a94fa42fe",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/976ab321e16bf9aacd6ed29848eb633bcc599052",
              "width": 64
            }
          ],
          "name": "Psycho, Pt. 2",
          "release_date": "2016-11-08",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:21UO4eAaNZ5kultgMBNEHD"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 161985,
        "explicit": true,
        "external_ids": {
          "isrc": "TCACT1646486"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/26OhjtaTamFocE08t83ml6"
        },
        "href": "https://api.spotify.com/v1/tracks/26OhjtaTamFocE08t83ml6",
        "id": "26OhjtaTamFocE08t83ml6",
        "is_local": false,
        "name": "Psycho, Pt. 2",
        "popularity": 77,
        "preview_url": "https://p.scdn.co/mp3-preview/7b98b3b81be1ec4bfed0eabde8d5d69d0fd4800b?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:26OhjtaTamFocE08t83ml6"
      },
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/507vscnpu2fPaKmA5nC3pX"
          },
          "href": "https://api.spotify.com/v1/albums/507vscnpu2fPaKmA5nC3pX",
          "id": "507vscnpu2fPaKmA5nC3pX",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/6ef689857cc22fa5973f815e523055fa5dd08244",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/b8e227950dbb0b670d8725963fc9925a01fcfcc1",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/91974dfcf2c0f10ead40411b8fb9153332bee311",
              "width": 64
            }
          ],
          "name": "Ain't Nobody Takin My Baby",
          "release_date": "2016-12-23",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:507vscnpu2fPaKmA5nC3pX"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 189231,
        "explicit": true,
        "external_ids": {
          "isrc": "TCACW1605973"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6VnqGxiMNexOe0kRmIsBw4"
        },
        "href": "https://api.spotify.com/v1/tracks/6VnqGxiMNexOe0kRmIsBw4",
        "id": "6VnqGxiMNexOe0kRmIsBw4",
        "is_local": false,
        "name": "Ain't Nobody Takin My Baby",
        "popularity": 74,
        "preview_url": "https://p.scdn.co/mp3-preview/606c1bf1b4bae3e8a70afd6d8c32d44066eaf432?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:6VnqGxiMNexOe0kRmIsBw4"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0lUL92det7mZ4DaHYmiUEC"
          },
          "href": "https://api.spotify.com/v1/albums/0lUL92det7mZ4DaHYmiUEC",
          "id": "0lUL92det7mZ4DaHYmiUEC",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/896e3f06b79792b93bb96ee3f3444a5a87ce845f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/7f5511ed5fd0c3d02ae19655a26a9b3ee6937f5b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/c09b87a7035848b413b642e6f3fa16a5992f4354",
              "width": 64
            }
          ],
          "name": "There's Really A Wolf",
          "release_date": "2017-05-05",
          "release_date_precision": "day",
          "total_tracks": 20,
          "type": "album",
          "uri": "spotify:album:0lUL92det7mZ4DaHYmiUEC"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 165853,
        "explicit": true,
        "external_ids": {
          "isrc": "USSM11606200"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3pndPhlQWjuSoXhcIIdBjv"
        },
        "href": "https://api.spotify.com/v1/tracks/3pndPhlQWjuSoXhcIIdBjv",
        "id": "3pndPhlQWjuSoXhcIIdBjv",
        "is_local": false,
        "name": "What They Want",
        "popularity": 74,
        "preview_url": "https://p.scdn.co/mp3-preview/ddbb456112c441e4d239b7751b08604cf29ea94f?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 11,
        "type": "track",
        "uri": "spotify:track:3pndPhlQWjuSoXhcIIdBjv"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0lUL92det7mZ4DaHYmiUEC"
          },
          "href": "https://api.spotify.com/v1/albums/0lUL92det7mZ4DaHYmiUEC",
          "id": "0lUL92det7mZ4DaHYmiUEC",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/896e3f06b79792b93bb96ee3f3444a5a87ce845f",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/7f5511ed5fd0c3d02ae19655a26a9b3ee6937f5b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/c09b87a7035848b413b642e6f3fa16a5992f4354",
              "width": 64
            }
          ],
          "name": "There's Really A Wolf",
          "release_date": "2017-05-05",
          "release_date_precision": "day",
          "total_tracks": 20,
          "type": "album",
          "uri": "spotify:album:0lUL92det7mZ4DaHYmiUEC"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 185400,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM11703768"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6HK4YGOpZr1ost68QP3ul0"
        },
        "href": "https://api.spotify.com/v1/tracks/6HK4YGOpZr1ost68QP3ul0",
        "id": "6HK4YGOpZr1ost68QP3ul0",
        "is_local": false,
        "name": "Ride Slow",
        "popularity": 72,
        "preview_url": "https://p.scdn.co/mp3-preview/6c6495e5809d6bf7d08b7da6cc29c03e29756f0b?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:6HK4YGOpZr1ost68QP3ul0"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy"
              },
              "href": "https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy",
              "id": "3aQeKQSyrW4qWr35idm0cy",
              "name": "T-Pain",
              "type": "artist",
              "uri": "spotify:artist:3aQeKQSyrW4qWr35idm0cy"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4hlDbXacT1aV15qY9kzSpB"
          },
          "href": "https://api.spotify.com/v1/albums/4hlDbXacT1aV15qY9kzSpB",
          "id": "4hlDbXacT1aV15qY9kzSpB",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/8a04eeea9a958cb586541918197eca37268695f2",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/aee91002e9173ac878501cf7689b42402e2bc189",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/9e325367778ae00722db14319d4057cae1ba4b82",
              "width": 64
            }
          ],
          "name": "1UP",
          "release_date": "2019-02-27",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:4hlDbXacT1aV15qY9kzSpB"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy"
            },
            "href": "https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy",
            "id": "3aQeKQSyrW4qWr35idm0cy",
            "name": "T-Pain",
            "type": "artist",
            "uri": "spotify:artist:3aQeKQSyrW4qWr35idm0cy"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 222004,
        "explicit": true,
        "external_ids": {
          "isrc": "QMKSC1900044"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5cpiUTX2VJn5JN7myo2XaD"
        },
        "href": "https://api.spotify.com/v1/tracks/5cpiUTX2VJn5JN7myo2XaD",
        "id": "5cpiUTX2VJn5JN7myo2XaD",
        "is_local": false,
        "name": "Here It Comes (feat. Russ)",
        "popularity": 57,
        "preview_url": "https://p.scdn.co/mp3-preview/6bc8606269fed2362b3000bda7bf1e308fd2bae0?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 11,
        "type": "track",
        "uri": "spotify:track:5cpiUTX2VJn5JN7myo2XaD"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/21WS9wngs9AqFckK7yYJPM"
              },
              "href": "https://api.spotify.com/v1/artists/21WS9wngs9AqFckK7yYJPM",
              "id": "21WS9wngs9AqFckK7yYJPM",
              "name": "PnB Rock",
              "type": "artist",
              "uri": "spotify:artist:21WS9wngs9AqFckK7yYJPM"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2sCwWLX6DJgjCACS0iEBHD"
          },
          "href": "https://api.spotify.com/v1/albums/2sCwWLX6DJgjCACS0iEBHD",
          "id": "2sCwWLX6DJgjCACS0iEBHD",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/5e49036d2121a0e78c88b6cee6d4c7ede65045c3",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/2778d5e29acc8af4be38df90042f2524267393c6",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/1d712bb91059f2cd45133b3baba6f493ea15547f",
              "width": 64
            }
          ],
          "name": "Catch These Vibes",
          "release_date": "2017-11-17",
          "release_date_precision": "day",
          "total_tracks": 18,
          "type": "album",
          "uri": "spotify:album:2sCwWLX6DJgjCACS0iEBHD"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/21WS9wngs9AqFckK7yYJPM"
            },
            "href": "https://api.spotify.com/v1/artists/21WS9wngs9AqFckK7yYJPM",
            "id": "21WS9wngs9AqFckK7yYJPM",
            "name": "PnB Rock",
            "type": "artist",
            "uri": "spotify:artist:21WS9wngs9AqFckK7yYJPM"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 232857,
        "explicit": true,
        "external_ids": {
          "isrc": "USAT21704677"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1ysDVWxBj5Set0fA05TcyP"
        },
        "href": "https://api.spotify.com/v1/tracks/1ysDVWxBj5Set0fA05TcyP",
        "id": "1ysDVWxBj5Set0fA05TcyP",
        "is_local": false,
        "name": "Issues (feat. Russ)",
        "popularity": 65,
        "preview_url": "https://p.scdn.co/mp3-preview/21ffaa9a1fa3c2f428916afd5ee79c796a0ad65a?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:1ysDVWxBj5Set0fA05TcyP"
      },
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy"
              },
              "href": "https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy",
              "id": "3aQeKQSyrW4qWr35idm0cy",
              "name": "T-Pain",
              "type": "artist",
              "uri": "spotify:artist:3aQeKQSyrW4qWr35idm0cy"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/15V4ELoBOJI9hD2Rjco8Xc"
          },
          "href": "https://api.spotify.com/v1/albums/15V4ELoBOJI9hD2Rjco8Xc",
          "id": "15V4ELoBOJI9hD2Rjco8Xc",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/414f88cc2b271d5da2d4fb831f165206c6ba406a",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/7c858ea528cc2c2d1e4f00e42fa90eb36e2702de",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/482f2781609854772b518f77709d478d8dc48ac8",
              "width": 64
            }
          ],
          "name": "1UP",
          "release_date": "2019-02-26",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:15V4ELoBOJI9hD2Rjco8Xc"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3aQeKQSyrW4qWr35idm0cy"
            },
            "href": "https://api.spotify.com/v1/artists/3aQeKQSyrW4qWr35idm0cy",
            "id": "3aQeKQSyrW4qWr35idm0cy",
            "name": "T-Pain",
            "type": "artist",
            "uri": "spotify:artist:3aQeKQSyrW4qWr35idm0cy"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 222004,
        "explicit": false,
        "external_ids": {
          "isrc": "QMKSC1900056"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1HbBa0ZhAEYm2yS0I1cCvj"
        },
        "href": "https://api.spotify.com/v1/tracks/1HbBa0ZhAEYm2yS0I1cCvj",
        "id": "1HbBa0ZhAEYm2yS0I1cCvj",
        "is_local": false,
        "name": "Here It Comes (feat. Russ)",
        "popularity": 42,
        "preview_url": "https://p.scdn.co/mp3-preview/0cb94a50ff6a283777f40a645f2f6e06eca4790c?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 11,
        "type": "track",
        "uri": "spotify:track:1HbBa0ZhAEYm2yS0I1cCvj"
      },
      {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
              },
              "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
              "id": "1z7b1Pr1rSlvWRzsW3HOrS",
              "name": "Russ",
              "type": "artist",
              "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7CC9iqq2JZ3j4jF9SNNLL7"
          },
          "href": "https://api.spotify.com/v1/albums/7CC9iqq2JZ3j4jF9SNNLL7",
          "id": "7CC9iqq2JZ3j4jF9SNNLL7",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/fdaba5784953973414f110c6b45aba4adab7c203",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/229402b5290597fc21b7bb86ac05d66daedad68f",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/86ce1dff199e5d3725945911c373c603231ddd07",
              "width": 64
            }
          ],
          "name": "Just In Case",
          "release_date": "2018-12-23",
          "release_date_precision": "day",
          "total_tracks": 3,
          "type": "album",
          "uri": "spotify:album:7CC9iqq2JZ3j4jF9SNNLL7"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS"
            },
            "href": "https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS",
            "id": "1z7b1Pr1rSlvWRzsW3HOrS",
            "name": "Russ",
            "type": "artist",
            "uri": "spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 215555,
        "explicit": true,
        "external_ids": {
          "isrc": "TCADZ1886738"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1pNAf6W7POwjOD8x8mWf8G"
        },
        "href": "https://api.spotify.com/v1/tracks/1pNAf6W7POwjOD8x8mWf8G",
        "id": "1pNAf6W7POwjOD8x8mWf8G",
        "is_local": false,
        "name": "Nobody Knows",
        "popularity": 71,
        "preview_url": "https://p.scdn.co/mp3-preview/0c9e55fe4e52684fd9ce6a1a447cc37230a6b689?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:1pNAf6W7POwjOD8x8mWf8G"
      }
    ],
    "limit": 10,
    "next": "https://api.spotify.com/v1/search?query=russ&type=track&market=US&offset=10&limit=10",
    "offset": 0,
    "previous": null,
    "total": 10092
  }
}